[tool.poetry]
name="document-aware-qa-service"
version="0.1.0"
description="Document Aware RAG Backend"
authors=["Guru brahmam"]
readme="README.md"
license="GPL v3"
repository="https://github.com/Vgurubrahmam/document_aware_qa_service"
keywords=["rag","qa","openai","fastapi","document"]
classifiers=[
    "Intended Audience :: Developers",
    "license :: OSI Approved ::GPL v3 License",
    "Programming Language:: Python :: 3",
    "Programming Language :: python :: 3.11",
]
package-mode=false

[tool.poetry.dependencies]
python="^3.11"
fastapi="^0.110.0"
uvicorn="^0.29.0"
openai="^1.12.0"
sqlalchemy="^2.0"
pydantic="^2.6"
python-multipart="^0.0.9"
aiofiles="^23.2.1"
python-dotenv="^1.0.1"
pydantic-settings="2.1.0"

[tool.poetry.group.dev.dependencies]
black="^24.3"
mypy="^1.8"
pytest="^8.1"

[build-system]
requires=["poetry-core"]
build-backend=["poetry.core.masonry.api"]